import { ConEsoNo, Decisiones, ElMelomano, EnPalabras, Ilusrado, NiEnPedo, Refumany, Teg, Tekbio } from "../public/img/games";

export const games = [
    {
      id: 0,
      name: "Decisiones de Mierda",
      image: Decisiones,
      description:
        "¿Crees que tus amigos toman malas decisiones? Conocé nuevos aspectos oscuros (muy oscuros) de tus amigos...",
      price: "4990",
      players: "2 - 4",
      age: "+18",
    },
    {
      id: 1,
      name: "En palabras - Desconectados",
      image: EnPalabras,
      description: "El juego de palabras divertido y desafiante para toda la familia.",
      price: "3500",
      players: "2 - 8",
      age: "7",
    },
    {
      id: 2,
      name: "El melómano",
      image: ElMelomano,
      description: "Demuestra tus conocimientos musicales en este emocionante juego de preguntas y respuestas.",
      price: "4200",
      players: "3+",
      age: "12",
    },
    {
      id: 3,
      name: "Ni en pedo",
      image: NiEnPedo,
      description: "El juego de desafíos y decisiones que te hará reír como nunca.",
      price: "3800",
      players: "4+",
      age: "18",
    },
    {
      id: 4,
      name: "Con eso no se jode",
      image: ConEsoNo,
      description: "Pon a prueba tu capacidad para improvisar respuestas graciosas en este juego de humor.",
      price: "4500",
      players: "3 - 10",
      age: "16",
    },
    {
      id: 5,
      name: "Refumanyi",
      image: Refumany,
      description: "Descubre quién conoce mejor a quién en este juego de revelar secretos.",
      price: "3900",
      players: "4+",
      age: "15",
    },
    {
      id: 6,
      name: "TEG",
      image: Teg,
      description: "El clásico juego de estrategia y conquista para disfrutar en largas partidas.",
      price: "5500",
      players: "2 - 6",
      age: "12",
    },
    {
      id: 7,
      name: "TK-bió",
      image: Tekbio,
      description: "Pon a prueba tus conocimientos de biología en este juego educativo y divertido.",
      price: "3200",
      players: "2+",
      age: "10",
    },
    {
      id: 8,
      name: "El ilustrado",
      image: Ilusrado,
      description: "Demuestra tu creatividad y habilidades de dibujo en este juego de adivinanzas.",
      price: "4200",
      players: "3+",
      age: "8",
    },
  ];
  
